### ISSUE TITLE
Another language!?

### ISSUE THREAD

**Issue by haskellcamargo** [mermaid-language/mermaid#9]
@takanuva won't be happy. :stuck_out_tongue:

**Comment by robotlolita** [comment]
Prepare-se para as linguagens!
Linguagens em dobro!
Para proteger o mundo do PHP!
Para desunir os programadores de nossa nação!
Para denunciar os males do Java e do JavaScript!
Para estender o nosso poder às estrelas!
Quil!
Eu mesmë!
Equipe Smalltalkers decolando na velocidade da luz!
Renda-se agora ou preparem-se para usá-las!
